use super::{SolveAction, SolveStep, SteppableSolver};
use crate::maze::{Direction, MazeGrid};

/// Wall Follower (Right-Hand Rule) maze solver.
///
/// Simulates following the right wall. At each step the solver attempts to:
/// 1. Turn right and move forward.
/// 2. If blocked, move straight.
/// 3. If blocked, turn left and move.
/// 4. If all three are blocked, turn around (180 degrees).
///
/// This algorithm always finds the exit in simply-connected (perfect) mazes
/// generated by DFS, Kruskal, Prim, etc. It does **not** guarantee the
/// shortest path.
///
/// The turn_right/turn_left operations are generalized using the topology's
/// direction array: turn_right = next direction in the array, turn_left =
/// previous direction in the array.
pub struct WallFollowerSolver {
    current: u32,
    facing: Direction,
    start: u32,
    end: u32,
    done: bool,
    found: bool,
    /// Trail of cells visited in order (may contain duplicates when backtracking).
    trail: Vec<u32>,
    /// The cleaned solution path (no loops).
    solution_path: Vec<u32>,
    /// Whether we have emitted the initial Visit for the start cell.
    started: bool,
    /// Cached directions array from the maze topology.
    directions: &'static [Direction],
    /// Max steps to prevent infinite loops on non-standard topologies.
    max_steps: u32,
    step_count: u32,
}

impl WallFollowerSolver {
    pub fn new(cell_count: u32, start: u32, end: u32) -> Self {
        WallFollowerSolver {
            current: start,
            facing: Direction::EAST,
            start,
            end,
            done: false,
            found: false,
            trail: Vec::new(),
            solution_path: Vec::new(),
            started: false,
            directions: Direction::all_rect(),
            max_steps: cell_count * 10, // safety limit
            step_count: 0,
        }
    }

    /// Turn 90 degrees clockwise using the direction rotation array.
    fn turn_right(&self, dir: Direction) -> Direction {
        let dirs = self.directions;
        let len = dirs.len();
        for (i, &d) in dirs.iter().enumerate() {
            if d == dir {
                return dirs[(i + 1) % len];
            }
        }
        // Fallback: return the first direction
        dirs[0]
    }

    /// Turn 90 degrees counter-clockwise using the direction rotation array.
    fn turn_left(&self, dir: Direction) -> Direction {
        let dirs = self.directions;
        let len = dirs.len();
        for (i, &d) in dirs.iter().enumerate() {
            if d == dir {
                return dirs[(i + len - 1) % len];
            }
        }
        // Fallback: return the first direction
        dirs[0]
    }

    /// Turn 180 degrees using the maze's opposite direction.
    fn turn_around(&self, dir: Direction, maze: &dyn MazeGrid) -> Direction {
        maze.opposite(dir)
    }

    /// Try to move from `cell` in direction `dir`. Returns the neighbor cell if
    /// there is no wall and a neighbor exists.
    fn try_move(cell: u32, dir: Direction, maze: &dyn MazeGrid) -> Option<u32> {
        if maze.has_wall(cell, dir) {
            return None;
        }
        let neighbors = maze.neighbors(cell);
        neighbors
            .iter()
            .find(|&&(_, d)| d == dir)
            .map(|&(n, _)| n)
    }

    /// Extract a simple path from the trail by removing loops.
    /// For each cell, we keep only the *last* occurrence, effectively
    /// short-cutting any loops the wall follower took.
    fn extract_path(&mut self) {
        self.solution_path.clear();
        let len = self.trail.len();
        if len == 0 {
            return;
        }

        // Build a map of cell -> last index in trail.
        let max_cell = self.trail.iter().copied().max().unwrap_or(0) as usize;
        let mut last_index = vec![0usize; max_cell + 1];
        for (i, &cell) in self.trail.iter().enumerate() {
            last_index[cell as usize] = i;
        }

        let mut i = 0;
        while i < len {
            let cell = self.trail[i];
            self.solution_path.push(cell);
            if cell == self.end {
                break;
            }
            let li = last_index[cell as usize];
            // Jump past the loop
            i = li + 1;
        }
    }
}

impl SteppableSolver for WallFollowerSolver {
    fn step(&mut self, maze: &dyn MazeGrid) -> Option<SolveStep> {
        if self.done {
            return None;
        }

        // Check step limit to prevent infinite loops
        self.step_count += 1;
        if self.step_count > self.max_steps {
            self.done = true;
            return None;
        }

        // Cache directions from maze on first use
        if !self.started {
            self.directions = maze.directions();
            // Set initial facing to first available direction
            self.facing = self.directions[0];
        }

        // First call: emit the start cell.
        if !self.started {
            self.started = true;
            self.trail.push(self.current);

            if self.current == self.end {
                self.done = true;
                self.found = true;
                self.solution_path.push(self.current);
                return Some(SolveStep {
                    cell: self.current,
                    action: SolveAction::FoundGoal,
                });
            }

            return Some(SolveStep {
                cell: self.current,
                action: SolveAction::Visit,
            });
        }

        // Right-hand rule: try right, straight, left, then behind.
        let right = self.turn_right(self.facing);
        let straight = self.facing;
        let left = self.turn_left(self.facing);
        let behind = self.turn_around(self.facing, maze);

        let (next_cell, new_facing) =
            if let Some(n) = Self::try_move(self.current, right, maze) {
                (n, right)
            } else if let Some(n) = Self::try_move(self.current, straight, maze) {
                (n, straight)
            } else if let Some(n) = Self::try_move(self.current, left, maze) {
                (n, left)
            } else if let Some(n) = Self::try_move(self.current, behind, maze) {
                (n, behind)
            } else {
                // Completely walled in (isolated cell). Should not happen in a
                // connected maze, but handle gracefully.
                self.done = true;
                return None;
            };

        self.current = next_cell;
        self.facing = new_facing;
        self.trail.push(self.current);

        if self.current == self.end {
            self.done = true;
            self.found = true;
            self.extract_path();
            return Some(SolveStep {
                cell: self.current,
                action: SolveAction::FoundGoal,
            });
        }

        Some(SolveStep {
            cell: self.current,
            action: SolveAction::Visit,
        })
    }

    fn path(&self) -> Option<&[u32]> {
        if self.found {
            Some(&self.solution_path)
        } else {
            None
        }
    }

    fn reset(&mut self, start: u32, end: u32) {
        self.current = start;
        self.facing = Direction::EAST;
        self.start = start;
        self.end = end;
        self.done = false;
        self.found = false;
        self.trail.clear();
        self.solution_path.clear();
        self.started = false;
        self.step_count = 0;
    }

    fn is_done(&self) -> bool {
        self.done
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::maze::RectGrid;
    use crate::generate::{DfsGenerator, SteppableGenerator};
    use crate::rng::Xoshiro256;

    fn generate_maze(width: u32, height: u32, seed: u64) -> RectGrid {
        let mut grid = RectGrid::new(width, height);
        let mut rng = Xoshiro256::new(seed);
        let mut gen = DfsGenerator::new(grid.cell_count(), 0);
        while gen.step(&mut grid, &mut rng).is_some() {}
        grid
    }

    #[test]
    fn test_wall_follower_finds_path() {
        let grid = generate_maze(10, 10, 42);
        let start = 0;
        let end = grid.cell_count() - 1;
        let mut solver = WallFollowerSolver::new(grid.cell_count(), start, end);

        let mut steps = 0;
        while let Some(_step) = solver.step(&grid) {
            steps += 1;
            // Safety limit to prevent infinite loops during testing.
            assert!(steps < 10_000, "Wall follower did not terminate");
        }

        assert!(solver.is_done());
        assert!(solver.path().is_some());
        let path = solver.path().unwrap();
        assert_eq!(path[0], start);
        assert_eq!(*path.last().unwrap(), end);
        assert!(path.len() >= 2);
        assert!(steps > 0);
    }

    #[test]
    fn test_wall_follower_path_is_valid() {
        let grid = generate_maze(8, 8, 99);
        let start = 0;
        let end = 63;
        let mut solver = WallFollowerSolver::new(grid.cell_count(), start, end);

        while solver.step(&grid).is_some() {}

        let path = solver.path().unwrap();
        for window in path.windows(2) {
            let from = window[0];
            let to = window[1];
            let neighbors = grid.neighbors(from);
            let neighbor_entry = neighbors.iter().find(|&&(n, _)| n == to);
            assert!(
                neighbor_entry.is_some(),
                "Path cells {} and {} are not neighbors",
                from,
                to
            );
            let (_, dir) = *neighbor_entry.unwrap();
            assert!(
                !grid.has_wall(from, dir),
                "Wall exists between {} and {}",
                from,
                to
            );
        }
    }

    #[test]
    fn test_wall_follower_start_equals_end() {
        let grid = generate_maze(5, 5, 1);
        let mut solver = WallFollowerSolver::new(grid.cell_count(), 0, 0);

        let step = solver.step(&grid);
        assert!(step.is_some());
        assert!(matches!(step.unwrap().action, SolveAction::FoundGoal));
        assert!(solver.is_done());
        assert_eq!(solver.path().unwrap(), &[0]);
    }

    #[test]
    fn test_wall_follower_various_sizes() {
        for &(w, h, seed) in &[(5, 5, 10), (15, 15, 77), (20, 10, 200)] {
            let grid = generate_maze(w, h, seed);
            let start = 0;
            let end = grid.cell_count() - 1;
            let mut solver = WallFollowerSolver::new(grid.cell_count(), start, end);

            let mut steps = 0;
            while solver.step(&grid).is_some() {
                steps += 1;
                assert!(steps < 50_000, "Wall follower did not terminate for {}x{}", w, h);
            }

            assert!(
                solver.path().is_some(),
                "Failed for {}x{} seed={}",
                w,
                h,
                seed
            );
        }
    }

    #[test]
    fn test_wall_follower_simple_corridor() {
        let mut grid = RectGrid::new(5, 1);
        // Open a straight corridor: 0-1-2-3-4
        grid.remove_wall(0, Direction::EAST);
        grid.remove_wall(1, Direction::EAST);
        grid.remove_wall(2, Direction::EAST);
        grid.remove_wall(3, Direction::EAST);

        let mut solver = WallFollowerSolver::new(5, 0, 4);
        while solver.step(&grid).is_some() {}

        let path = solver.path().unwrap();
        assert_eq!(path, &[0, 1, 2, 3, 4]);
    }

    #[test]
    fn test_wall_follower_reset() {
        let grid = generate_maze(6, 6, 55);
        let mut solver = WallFollowerSolver::new(grid.cell_count(), 0, 35);

        let mut steps = 0;
        while solver.step(&grid).is_some() {
            steps += 1;
            assert!(steps < 50_000);
        }
        assert!(solver.path().is_some());

        solver.reset(5, 30);
        assert!(!solver.is_done());
        assert!(solver.path().is_none());

        steps = 0;
        while solver.step(&grid).is_some() {
            steps += 1;
            assert!(steps < 50_000);
        }
        assert!(solver.is_done());
        assert!(solver.path().is_some());
        let path = solver.path().unwrap();
        assert_eq!(path[0], 5);
        assert_eq!(*path.last().unwrap(), 30);
    }
}
